FROM mariadb:11-ubi9

COPY db-create.sh /usr/local/bin/db-create
COPY db-remove.sh /usr/local/bin/db-remove
COPY db-exists.sh /usr/local/bin/db-exists
COPY db-wait.sh /usr/local/bin/db-wait
COPY dbs-list.sh /usr/local/bin/dbs-list
